Renaming as needed
powerjg/gem5 pull request #3
Opened 2017-05-04 22:21 UTC by swapnilh

Change-Id: I8ca9e965582abbf1c6761c920398b464912b3893

2017-05-04 22:34 UTC, powerjg requested changes

2017-05-04 22:34 UTC, powerjg commented on configs/daxpy/run-accel.py
> +    elif exit_event.getCause() == "simulate() limit reached":
This actually isn't right. The target should call exit at the end of execution. There must be a bug in the user-mode app.

2017-05-05 15:35 UTC, swapnilh commented
You were right. The correct exit message is - 'exiting with last active thread context'. I think you had a suggested fix, but I amended the earlier commit and forced it through, so now I can't see it.

2017-05-05 18:11 UTC, powerjg approved these changes

2017-05-05 18:11 UTC, merged